name: Docker Build Per Platform

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  build_docker:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm]
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "PLATFORM=${{ matrix.platform }}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build nps for ${{ matrix.platform }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.nps
        platforms: ${{ matrix.platform }}
        push: false
        tags: nps:${{ env.RELEASE_VERSION }}-${{ matrix.platform }}
        outputs: type=docker,dest=/tmp/nps-${{ matrix.platform }}.tar

    - name: Build npc for ${{ matrix.platform }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.npc
        platforms: ${{ matrix.platform }}
        push: false
        tags: npc:${{ env.RELEASE_VERSION }}-${{ matrix.platform }}
        outputs: type=docker,dest=/tmp/npc-${{ matrix.platform }}.tar

    - name: Verify built images
      run: |
        echo "Built for platform: ${{ matrix.platform }}"
        ls -la /tmp/*-${{ matrix.platform }}.tar
